#端口
server:
  port: 80

  #日志配置
#logging:
#  path: /springboot/log
#    #    pattern:
#    #      console: %d{yyyy-MM-dd}[%thread]%-5level%logger{50}-%msg%n
#    #      file: %d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n
#    level: com.yjdz.shopping.dao=debug

logging:
  level:
    root: info
    com.bestvike: debug
  #    org.springframework.security: warn
  # 默认日志文件名
  # file: log
  # 默认日志路径
  path: /springboot/log
  # logback.xml路径，默认为classpath:logback.xml
  # config: ./logback.xml

  #Mybatis扫描
  #    mybatis:
  #     mapper-locations: classpath*:mapper/*.xml
mybatis:
  #  type-aliases-package: com.yjdz.zncdz.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://118.24.182.66:3306/znb_huiyiyi_top?useUnicode=true&characterEncoding=UTF8&serverTimezone=CTT
    #    username: znb_huiyiyi_top
    #    password: mEE26SxN7wMGLf5H
    url: jdbc:mysql://localhost:3306/znb_huiyiyi_top?useUnicode=true&characterEncoding=UTF8&serverTimezone=CTT
    username: root
    password: 123123

      #      type: com.alibaba.druid.pool.DruidDataSource
      #      #最大活跃数
      #      maxActive: 20
      #      #初始化数量
      #      initialSize: 1
      #      #最大连接等待超时时间
      #      maxWait: 60000
      #      #打开PSCache，并且指定每个连接PSCache的大小
      #      poolPreparedStatements: true
      #      maxPoolPreparedStatementPerConnectionSize: 20
      #      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #      minIdle: 1
      #      timeBetweenEvictionRunsMillis: 60000
      #      minEvictableIdleTimeMillis: 300000
      #      validationQuery: select 1 from dual
    #      testWhileIdle: true
    #      testOnBorrow: false
    #      testOnReturn: false
    #      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    #      filters: stat, wall, log4j
